project:
  type: website
  
website:
  title: "Franco J S Silva"

  navbar:
    background: primary
    search: true
    right:
      - text: "About"
        file: "personal/about.qmd"
      # - sidebar:teaching

      - icon: github
        href: https://github.com/jefferds
      - icon: twitter 
        href: https://twitter.com/FrancoJefferds
      - icon: linkedin 
        href: https://www.linkedin.com/in/franco-j-s-silva-15666627/

  sidebar:

    - id: teaching
      title: "Ensino"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - "teaching/solidsmechanics/solidsmechanics1.qmd"


page-footer: 
  center: "_Copyright 2022, Franco Jefferds dos S. Silva_ -- O código está sob [MIT license](https://opensource.org/licenses/MIT) e o texto e medias estão sob [CC BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0)"

format:
  html:
    theme: united
    css: styles.css
    toc: true
